### ISSUE TITLE
Indonesian

### ISSUE THREAD

**Issue by tofula** [MicrosoftDocs/azure-docs.cs-cz#136]
Dear team, is the Indonesina supported for customization now? I can see it available in  the Custom Translator web app, but not listed on this page. Could you please confirm? Thanks.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 3452c464-0135-aaab-5e96-a88f3144e378
* Version Independent ID: 3816f475-bf5f-b5b4-9458-5cc70e93d55e
* Content: [Podpora jazyků – Translator Text API - Azure Cognitive Services](https://docs.microsoft.com/cs-cz/azure/cognitive-services/translator/language-support#customization)
* Content Source: [articles/cognitive-services/Translator/language-support.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/live/articles/cognitive-services/Translator/language-support.md)
* Service: **cognitive-services**
* Sub-service: **translator-text**
* GitHub Login: @v-pawal
* Microsoft Alias: **v-jansko**

**Comment by CeciAc** [comment]
Hello, @tofula 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by tofula** [comment]
Dear team,
I think this is relevant for the documentation. Let me reformulate it - so my question is "Is the Indonesian language missing in the list of supported languages on your page?"

Thanks

**Comment by Jann-Skotdal** [comment]
@tofula : Indonesian was recently added. We are updating the documentation.

**Comment by tofula** [comment]
Great, thank you for the confirmation. I apreciate you support.
