### ISSUE TITLE
iSEiK

### ISSUE THREAD

**Issue by SEiKjan** [MicrosoftDocs/azure-docs.cs-cz#39]
?

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: e9e02a6a-cd93-700d-0073-cca2f6166d67
* Version Independent ID: 215511e6-6599-4aac-5592-635640a635cb
* Content: [Použít pro přístup k zabezpečeným prostředkům bez zásahu uživatele Azure AD v2.0](https://docs.microsoft.com/cs-cz/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)
* Content Source: [articles/active-directory/develop/v2-oauth2-client-creds-grant-flow.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/live/articles/active-directory/develop/v2-oauth2-client-creds-grant-flow.md)
* Service: **active-directory**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by LisandroSu** [comment]
Hello, @SEiKjan 
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @SEiKjan
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @SEiKjan
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @SEiKjan ,
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team
