### ISSUE TITLE
Unable to perform the update via ARM

### ISSUE THREAD

**Issue by ZdenekSohnel** [MicrosoftDocs/azure-docs.cs-cz#40]
I tried to use the templates from this article, but ended up with this error message:

Deployment failed. Correlation ID: XXX. {
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.Insights' for api version '2018-05-01-preview'."
  }
}

I saw that there are differences in the validation like type property value had to be different. I also had to specify resource for the parent AI to get a bit forward. I used schema from here: https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2018-05-01-preview/Microsoft.Insights.json

Here is my piece of template:

 {
            "apiVersion": "2018-05-01-preview",
            "name": "slowpageloadtime",
            "type": "Microsoft.Insights/ProactiveDetectionConfigs",
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[variables('aiDependsOn')]"
            ],
            "properties": {
                "name": "slowpageloadtime",
                "sendEmailsToSubscriptionOwners": false,
                "customEmails": [
                    "test@test.com"
                ],
                "enabled": true
            }
        },

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 4b22256b-6d3e-f8df-9309-477e181f6a8f
* Version Independent ID: b54c4e18-60e2-470b-5e12-ff25a4ecf143
* Content: [Konfigurace nastavení pravidla inteligentního zjišťování Azure Application Insights pomocí šablon Azure Resource Manageru](https://docs.microsoft.com/cs-cz/azure/application-insights/app-insights-proactive-arm-config)
* Content Source: [articles/application-insights/app-insights-proactive-arm-config.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/live/articles/application-insights/app-insights-proactive-arm-config.md)
* Service: **application-insights**
* GitHub Login: @harelbr
* Microsoft Alias: **harelbr**

**Comment by ZdenekSohnel** [comment]
Thank you guys for your help, I moved ProactiveDetectionConfigs into resources under the parent AI resource and it works okay now.

**Comment by LisandroSu** [comment]
Hello, @ZdenekSohnel ,
 
Thanks once again for your comment.

I'll be closing the issue now.

Kind regards,
Microsoft DOCS International Team
