### ISSUE TITLE
AUFS-DKMS dependency failing on Raspberry 4 as AUFS kernel support has been dropped

### ISSUE THREAD

**Issue by rheingold** [MicrosoftDocs/azure-docs.cs-cz#481]
After trying to prototype this solution od RPi 4, I stumbled across AUFS-DKMS dependency failing for docker on Raspberry 4 as it seems that AUFS kernel support has been dropped (see here for example: https://www.raspberrypi.org/forums/viewtopic.php?t=243691). Maybe these workaround might help, but different package from MS repository would be perhaps more appreciated:
After moby-engine has been installed: "apt-get install -y docker-ce" and then "apt remove aufs-dkms", or maybe the workaround "curl -sL get.docker.com | sed 's/9)/10)/' | sh" might help (but haven't tested myself).

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: a3b8296d-c923-e990-dcad-35ef2b908a2a
* Version Independent ID: 5f85fd7b-f2b6-b3b1-6be2-b6054bb33507
* Content: [Nainstalovat Azure IoT Edge pro Linux](https://docs.microsoft.com/cs-cz/azure/iot-edge/how-to-install-iot-edge-linux#feedback)
* Content Source: [articles/iot-edge/how-to-install-iot-edge-linux.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/master/articles/iot-edge/how-to-install-iot-edge-linux.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by srvbpigh** [comment]
Hello, @rheingold
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rheingold 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43144

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
