### ISSUE TITLE
Trying this with Microsoft Mixed reality device produced an error

### ISSUE THREAD

**Issue by OCDtraining** [MicrosoftDocs/azure-docs.cs-cz#482]
I was able to follow the tutorial to the point where I clicked on Debug &gt; Start debugging but Visual Studio produced an error: "Bootstrapper could not connect to machine." When I clicked on OK it gave me more errors: 

"DEP6957: Failed to connect to device '127.0.0.1' using Universal Authentication. Please verify the correct remote authentication mode is specified in the project debug settings."

and

'Windows::UI::ViewManagement::IApplicationView2::SuppressSystemOverlays::set': marked as deprecated

This is supposed to work also on WMR devices, am I right? What should I do differently to be able to continue placing spatial anchors?

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 123315ce-4945-a613-4cb6-cbfe22ef9d42
* Version Independent ID: 17ef871c-3aa5-f67b-5c97-fcce3fb7df85
* Content: [Rychlý Start: Vytvoření aplikace pro HoloLens pomocí Unity](https://docs.microsoft.com/cs-cz/azure/spatial-anchors/quickstarts/get-started-unity-hololens)
* Content Source: [articles/spatial-anchors/quickstarts/get-started-unity-hololens.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/master/articles/spatial-anchors/quickstarts/get-started-unity-hololens.md)
* Service: **azure-spatial-anchors**
* GitHub Login: @craigktreasure
* Microsoft Alias: **crtreasu**

**Comment by srvbpigh** [comment]
Hello, @OCDtraining
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @OCDtraining

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43407

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
