### ISSUE TITLE
Old screenshots

### ISSUE THREAD

**Issue by michalmlaka** [MicrosoftDocs/azure-docs.cs-cz#495]
[Sem napište váš názor.]

Hi, It looks like, the private endpoint is not more in preview. Screenshots present it like preview feature.
---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 191d0067-67ee-212d-77f6-ffb1db64582f
* Version Independent ID: 71d5a250-17e6-8500-b6a3-3c46401a255c
* Content: [Integrace se službou Azure Private Link](https://docs.microsoft.com/cs-cz/azure/key-vault/general/private-link-service)
* Content Source: [articles/key-vault/general/private-link-service.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/master/articles/key-vault/general/private-link-service.md)
* Service: **key-vault**
* Sub-service: **general**
* GitHub Login: @ShaneBala-keyvault
* Microsoft Alias: **sudbalas**

**Comment by srvbpigh** [comment]
Hello, @michalmlaka
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @michalmlaka , 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @michalmlaka 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @michalmlaka 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
